### ISSUE TITLE
Framed Drawer Crash

### ISSUE THREAD

**Issue by SongSystem** [Buuz135/FunctionalStorage#123]
So, as it turns out, putting a normal drawer into the crafting table when changing a framed compacting drawer's outside texture crashes the game.

**Comment by Saereth** [comment]
using a slime block will also cause a render crash
https://gist.github.com/ShyNieke/fc3651e249bc61e50ac5dca0c704e186

Steps to reproduce

make a framed compacting drawer
put a block in crafting slot 1
put a slimeblock in crafting slot 2
put the framed drawer in crafting slot 3
crash
Expected behaviour
Have a nice barrel with a slime block as texture

And if you have a mod like tinkers work tables that render the items on the crafting table you crash anytime you try to load back in and the item has to be nbtedited out.

**Comment by Buuz135** [comment]
Fixed in https://github.com/Buuz135/FunctionalStorage/commit/aaf9b4f22d01fadc2ea893340eea30f49df83c4e backported to 1.18
