### ISSUE TITLE
[1.19.2] Creative vending upgrade not working

### ISSUE THREAD

**Issue by ahmut2008** [Buuz135/FunctionalStorage#167]
**Functional Storage Version:** 1.1.3

**Titanium Version:** 3.7.2-26

Drawer with creative vending upgrade shows that it has items inside but doesn't allow to pull items by hand or any kind of external storage mod.(I tried refined applied and integrated dynamics as external storage mods.)

**Comment by EndangeredNayla** [comment]
Duplicate for 1.18.2

**Comment by dboobis** [comment]
It seems the creative vending upgrade only works when applied to a drawer that already has items in it - and then it behaves as if you always have just as many items as were originally in the drawer (e.g. if you only have 1 item you can only ever pull out one item at a time, rather than a full stack). If you want to increase the available stack size, take out the upgrade, insert more items, then put the upgrade back in and this should work.

Probably not intended behaviour but I don't know enough about Java to submit a PR myself.

**Comment by Buuz135** [comment]
Duplicate #184
