### ISSUE TITLE
[1.19.2] Incorrect fluid count, kB misrepresented as MB

### ISSUE THREAD

**Issue by AriDeve** [Buuz135/FunctionalStorage#177]
**Functional Storage Version:** 1.1.3

**Titanium Version:** 3.7.3-27

Unless I am misunderstanding how this should work, title says it all, when fluids roll over a thousand buckets, count isn't shown as "xk B", but rather as "xM B". Encountered in FTB Skies.

![image](https://user-images.githubusercontent.com/37328719/233039180-9c5bd706-8224-46c5-aeed-6c19e0792b42.png)

**Comment by atealein** [comment]
![Screenshot 2023-04-29 at 11 04 19](https://user-images.githubusercontent.com/25322782/235294552-3d2fe10d-5882-45f4-a80d-8072954f46fc.png)

I can confirm this bug and clarify - the units of the drawer are showing wrongly M B instead of k B. 
To elaborate: 1 bucket (B) is 1000 mB ; 1 kB is in fact 1000 B or 1'000'000 mB ; 1 M B would be 1'000'000 buckets or 1000k B;

I have about 3200 buckets of liquid in this drawer, while it shows 3.2M B instead of 3.2kB
