### ISSUE TITLE
[Bug] Compacting drawer not compacting correctly

### ISSUE THREAD

**Issue by TheonlyTazz** [Buuz135/FunctionalStorage#49]
**Modpack**
DW20 1.18.2

**Modpack version**
1.5.1

**Describe the bug**
Drawer doesnt configure correctly when placing Copper ingots/blocks inside
works correctly when placing in nuggets first.

When placing in Quartz, it also compresses into Quartzblocks and Quartz Brick Blocks (which shouldnt be able to convert back to regular quartz)

**Steps to reproduce**
- Place drawer
- Fill in Copper Ingot
- no Copper Nugget in drawer

**Expected behaviour**
Configuration file to add custom rules (like in 1.16.5 Storage Drawers (i know, diffrent mod)

**Screenshots**
![image](https://user-images.githubusercontent.com/3908847/174428409-2dd9cd2c-e62f-4bdd-b5c7-8a4d2fa30b64.png)

**Additional information**
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/805

**Comment by WebDragon** [comment]
I wouldn't mind losing the ability to work backwards from Quartz Bricks -> Blocks, but would definitely mind losing the ability to go from Quartz Blocks <-> Nether Quartz, as that mechanic specifically has been part of the original storage drawers since the earliest I can recall of it

I didn't even know/realize until just now that Quartz Bricks were vanilla minecraft, because I use so little Quartz in general because it's such a pain mining in the new vanilla nether anymore let alone prior to this.

**Comment by quietust** [comment]
The Quartz -> Quartz Bricks behavior is actually a serious problem, because it doesn't take into account that 4 Quartz "compacts" into **4** Quartz Bricks and not 1 - if you insert 4 Quartz Bricks (crafted from 4 Quartz Blocks) into the drawer, the number of Quartz blocks increases by **16** instead of only 4, allowing quartz to be infinitely duplicated.
