### ISSUE TITLE
Compacting drawer crash

### ISSUE THREAD

**Issue by LoffyLV** [Buuz135/FunctionalStorage#54]
When you try to take out upgrade from compacting drawer that has any items inside it crashes client (server keeps going no problem), even if there is just couple items far below what non upgraded drawer holds.
Modpack - AllTheMods 7 (I'm just not sure if that's relevant and I don't know how to check if it's modpack specific or mod by itself issue)
Tried on both .18 and .19 mod versions.

**Comment by LoffyLV** [comment]
Ok, on further occasions regarding this, it seems this happens if you try to remove the upgrades from a drawer that is locked.

**Comment by TiphaineLAURENT** [comment]
If it can help, there is a crash report for the same bug:

[crash-2022-07-17_16.00.32-client.txt](https://github.com/Buuz135/FunctionalStorage/files/9127804/crash-2022-07-17_16.00.32-client.txt)

**Comment by kalutro** [comment]
This same issue happened to me and I believe I know why. The error I get is: `java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3`

I believe the code is checking each of the "Storage" slots for an item, I guess to check if removing the upgrade would be valid based on the number of items in the drawer. Regular drawers have four slots (indices 0 to 3), while the compacting drawer only has three slots (indices 0 to 2). When the drawer attempts to check the fourth slot (index 3) it crashes because that slot doesn't exist in the compacting drawer.

Now, I have also had the same crash trying to remove the pusher upgrade from the 'Utility' slots. Not sure if it's related.

This should be an easy fix and I am looking forward to it. Have a great day!
