### ISSUE TITLE
[Request] Add redstone output

### ISSUE THREAD

**Issue by Pentasis** [Buuz135/FunctionalStorage#7]
Either by default or as an upgrade. Have a drawer output a Redstone signal with a strength indicating its fullness.

Alternatively or additionally (and this is just a brainstorm thought) Add a redstone-controller that connects to the "network" that has a gui where you can set when a redstone signal is wirelessly transmitted at a certain level. The channel used to transmit is labeled with the contents of the drawer. Then add a wireless receiver which can be set to that channel.
E.g.  if a drawer containing oak logs would drop below (or above) X items, a signal would be sent over the "oak log" channel. Again, this is just a wild thought, just a redstone output would be fine.

**Comment by telemenar** [comment]
Out of curiosity what is your thought on the degree to which comparator working with the blocks would solve this problem rather than the block itself emitting redstone? 

Though obviously for the multi drawer blocks there is an interesting question as to how the comparator interacts with the different slots. Drawer equivalent to redstone low (least full slot) vs redstone high (most full slot) vs redstone (all slots combined)

**Comment by Pentasis** [comment]
I think you misunderstand my brainstorm-thought; no problem :) Just the drawer itself emitting redstone would be fine.
Personally I hardly ever use multi-drawers, so I have no idea how those work with redstone upgrades.

**Comment by TheWhiteWolves** [comment]
Any plans to add redstone compatibility to the drawers? I just came to trying to use a compacting drawer for a system, put down a comparator and got nothing which I very much wasn't expecting 🤨

**Comment by posicat** [comment]
I'd say for a multi-drawer output based on the item with the largest quantity.  If anyone wants it to be more specific they can use a single item box.  Either that or a checkbox on the drawer-page with the upgrades for which one(s) to report on, but that seems overly complex.
